# 準備

## Googleドライブのマウント

In [1]:

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## sys.pathの設定

以下では，Googleドライブのマイドライブ直下にDNN_codeフォルダを置くことを仮定しています．必要に応じて，パスを変更してください．

In [2]:
import sys
sys.path.append('/content/drive/My Drive/DNN_code')

# importと関数定義

In [3]:
import numpy as np
from common import functions

def print_vec(text, vec):
    print("*** " + text + " ***")
    print(vec)
    if isinstance(vec, (np.ndarray, )):
        print("shape: " + str(vec.shape))
    print("")


# 順伝播（単層・単ユニット）

In [4]:
# 順伝播（単層・単ユニット）

# 重み
W = np.array([[0.1], [0.2]])

## 試してみよう_配列の初期化
#W = np.zeros(2)
#W = np.ones(2)
#W = np.random.rand(2)
#W = np.random.randint(5, size=(2))

print_vec("重み", W)


# バイアス
b = 0.5

## 試してみよう_数値の初期化
#b = np.random.rand() # 0~1のランダム数値
#b = np.random.rand() * 10 -5  # -5~5のランダム数値

print_vec("バイアス", b)

# 入力値
x = np.array([2, 3])
print_vec("入力", x)


# 総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.relu(u)
print_vec("中間層出力", z)


*** 重み ***
[[0.1]
 [0.2]]
shape: (2, 1)

*** バイアス ***
0.5

*** 入力 ***
[2 3]
shape: (2,)

*** 総入力 ***
[1.3]
shape: (1,)

*** 中間層出力 ***
[1.3]
shape: (1,)



## 試してみよう_配列の初期化

In [5]:
W = np.zeros(2)
print_vec("重み", W)
W = np.ones(2)
print_vec("重み", W)
W = np.random.rand(2)
print_vec("重み", W)
W = np.random.randint(5, size=(2))
print_vec("重み", W)



*** 重み ***
[0. 0.]
shape: (2,)

*** 重み ***
[1. 1.]
shape: (2,)

*** 重み ***
[0.32250756 0.7401152 ]
shape: (2,)

*** 重み ***
[3 2]
shape: (2,)



## 試してみよう_数値の初期化


In [6]:
b = np.random.rand() # 0~1のランダム数値
print_vec("バイアス", b)
b = np.random.rand() * 10 -5  # -5~5のランダム数値
print_vec("バイアス", b)

*** バイアス ***
0.3970637094558579

*** バイアス ***
3.9586184801062796



# 順伝播（単層・複数ユニット）


In [7]:
# 順伝播（単層・複数ユニット）

# 重み
W = np.array([
    [0.1, 0.2, 0.3], 
    [0.2, 0.3, 0.4], 
    [0.3, 0.4, 0.5],
    [0.4, 0.5, 0.6]
])

## 試してみよう_配列の初期化
#W = np.zeros((4,3))
#W = np.ones((4,3))
#W = np.random.rand(4,3)
#W = np.random.randint(5, size=(4,3))


print_vec("重み", W)

# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec("バイアス", b)

# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec("入力", x)


#  総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.sigmoid(u)
print_vec("中間層出力", z)


*** 重み ***
[[0.1 0.2 0.3]
 [0.2 0.3 0.4]
 [0.3 0.4 0.5]
 [0.4 0.5 0.6]]
shape: (4, 3)

*** バイアス ***
[0.1 0.2 0.3]
shape: (3,)

*** 入力 ***
[ 1.  5.  2. -1.]
shape: (4,)

*** 総入力 ***
[1.4 2.2 3. ]
shape: (3,)

*** 中間層出力 ***
[0.80218389 0.90024951 0.95257413]
shape: (3,)



## 試してみよう_配列の初期化


In [8]:
W = np.zeros((4,3))
print_vec("重み", W)
W = np.ones((4,3))
print_vec("重み", W)
W = np.random.rand(4,3)
print_vec("重み", W)
W = np.random.randint(5, size=(4,3))
print_vec("重み", W)

*** 重み ***
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape: (4, 3)

*** 重み ***
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
shape: (4, 3)

*** 重み ***
[[0.24216154 0.62173265 0.86962215]
 [0.88387503 0.58060684 0.00355712]
 [0.86276673 0.02066122 0.04759282]
 [0.21982208 0.96366338 0.05581445]]
shape: (4, 3)

*** 重み ***
[[1 3 2]
 [4 3 1]
 [2 1 1]
 [2 3 1]]
shape: (4, 3)



# 順伝播（3層・複数ユニット）

In [9]:
# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    
    network['W1'] = np.array([
        [0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]
    ])
    network['W2'] = np.array([
        [0.1, 0.4],
        [0.2, 0.5],
        [0.3, 0.6]
    ])
    network['W3'] = np.array([
        [0.1, 0.3],
        [0.2, 0.4]
    ])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b2'] = np.array([0.1, 0.2])
    network['b3'] = np.array([1, 2])

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1
    
    # 1層の総出力
    z1 = functions.relu(u1)
    
    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3
    
    # 出力層の総出力
    y = u3
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", z1)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1, z2

# 入力値
x = np.array([1., 2.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

*** 入力 ***
[1. 2.]
shape: (2,)

##### ネットワークの初期化 #####
*** 重み1 ***
[[0.1 0.3 0.5]
 [0.2 0.4 0.6]]
shape: (2, 3)

*** 重み2 ***
[[0.1 0.4]
 [0.2 0.5]
 [0.3 0.6]]
shape: (3, 2)

*** 重み3 ***
[[0.1 0.3]
 [0.2 0.4]]
shape: (2, 2)

*** バイアス1 ***
[0.1 0.2 0.3]
shape: (3,)

*** バイアス2 ***
[0.1 0.2]
shape: (2,)

*** バイアス3 ***
[1 2]
shape: (2,)

##### 順伝播開始 #####
*** 総入力1 ***
[0.6 1.3 2. ]
shape: (3,)

*** 中間層出力1 ***
[0.6 1.3 2. ]
shape: (3,)

*** 総入力2 ***
[1.02 2.29]
shape: (2,)

*** 出力1 ***
[0.6 1.3 2. ]
shape: (3,)

出力合計: 3.9


 # 試してみよう
 ## _各パラメータのshapeを表示
 ## _ネットワークの初期値ランダム生成
    

In [10]:
# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    
    network['W1'] = np.random.rand(2,3)
    network['W2'] =  np.random.rand(3,2)
    network['W3'] = np.random.rand(2,2)
    network['b1'] = np.random.rand(3)
    network['b2'] = np.random.rand(2)
    network['b3'] = np.random.randint(3,size=(2))

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1
    
    # 1層の総出力
    z1 = functions.relu(u1)
    
    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3
    
    # 出力層の総出力
    y = u3
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", z1)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1, z2

# 入力値
x = np.array([1., 2.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

*** 入力 ***
[1. 2.]
shape: (2,)

##### ネットワークの初期化 #####
*** 重み1 ***
[[0.29866502 0.41675024 0.71931957]
 [0.38230448 0.82912757 0.23236154]]
shape: (2, 3)

*** 重み2 ***
[[0.27577427 0.92950778]
 [0.02975544 0.60796359]
 [0.77898775 0.85731387]]
shape: (3, 2)

*** 重み3 ***
[[0.99326563 0.5290503 ]
 [0.24988573 0.84006264]]
shape: (2, 2)

*** バイアス1 ***
[0.92763781 0.01515776 0.6476196 ]
shape: (3,)

*** バイアス2 ***
[0.68563658 0.94844882]
shape: (2,)

*** バイアス3 ***
[2 2]
shape: (2,)

##### 順伝播開始 #####
*** 総入力1 ***
[1.99091179 2.09016314 1.83166224]
shape: (3,)

*** 中間層出力1 ***
[1.99091179 2.09016314 1.83166224]
shape: (3,)

*** 総入力2 ***
[2.723715   5.64006935]
shape: (2,)

*** 出力1 ***
[1.99091179 2.09016314 1.83166224]
shape: (3,)

出力合計: 5.912737182864088


# 多クラス分類（2-3-4ネットワーク）

In [11]:
# 多クラス分類
# 2-3-4ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}
    network['W1'] = np.array([
        [0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]
    ])
    network['W2'] = np.array([
        [0.1, 0.4, 0.7, 1.0],
        [0.2, 0.5, 0.8, 1.1],
        [0.3, 0.6, 0.9, 1.2]
    ])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b2'] = np.array([0.1, 0.2, 0.3, 0.4])
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
x = np.array([1., 2.])

# 目標出力
d = np.array([0, 0, 0, 1])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[0.1 0.3 0.5]
 [0.2 0.4 0.6]]
shape: (2, 3)

*** 重み2 ***
[[0.1 0.4 0.7 1. ]
 [0.2 0.5 0.8 1.1]
 [0.3 0.6 0.9 1.2]]
shape: (3, 4)

*** バイアス1 ***
[0.1 0.2 0.3]
shape: (3,)

*** バイアス2 ***
[0.1 0.2 0.3 0.4]
shape: (4,)

##### 順伝播開始 #####
*** 総入力1 ***
[0.6 1.3 2. ]
shape: (3,)

*** 中間層出力1 ***
[0.6 1.3 2. ]
shape: (3,)

*** 総入力2 ***
[1.02 2.29 3.56 4.83]
shape: (4,)

*** 出力1 ***
[0.01602796 0.05707321 0.20322929 0.72366954]
shape: (4,)

出力合計: 1.0

##### 結果表示 #####
*** 出力 ***
[0.01602796 0.05707321 0.20322929 0.72366954]
shape: (4,)

*** 訓練データ ***
[0 0 0 1]
shape: (4,)

*** 誤差 ***
0.3234202933601941



#試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    #_ノードの構成を 3-5-4 に変更してみよう

In [12]:

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}
    network['W1'] = np.random.rand(3,5)
    network['W2'] = np.random.rand(5,4)
    network['b1'] = np.random.rand(5)
    network['b2'] = np.random.rand(4)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
x = np.array([1., 2.,3.])

# 目標出力
d = np.array([0, 0, 0, 1])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[0.80131306 0.03169131 0.67972892 0.41197406 0.96025025]
 [0.69870035 0.2819301  0.51075243 0.59904279 0.00249304]
 [0.41880173 0.92935815 0.71202254 0.15129761 0.10700537]]
shape: (3, 5)

*** 重み2 ***
[[0.94608515 0.37181985 0.96013767 0.5044489 ]
 [0.27608978 0.31519971 0.19338849 0.0384622 ]
 [0.31355863 0.98708582 0.60572382 0.0306216 ]
 [0.31188076 0.09361228 0.30557    0.91059728]
 [0.36036869 0.90881419 0.61458001 0.24457404]]
shape: (5, 4)

*** バイアス1 ***
[0.9392772  0.89725462 0.13090214 0.16489547 0.35491441]
shape: (5,)

*** バイアス2 ***
[0.28529147 0.94564688 0.0759135  0.90692131]
shape: (4,)

*** 重み1 ***
[[0.80131306 0.03169131 0.67972892 0.41197406 0.96025025]
 [0.69870035 0.2819301  0.51075243 0.59904279 0.00249304]
 [0.41880173 0.92935815 0.71202254 0.15129761 0.10700537]]
shape: (3, 5)

*** 重み2 ***
[[0.94608515 0.37181985 0.96013767 0.5044489 ]
 [0.27608978 0.31519971 0.19338849 0.0384622 ]
 [0.31355863 0.98708582 0.60572382 0.0306216 ]


# 回帰（2-3-2ネットワーク）

In [13]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.array([
        [0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]
    ])
    network['W2'] = np.array([
        [0.1, 0.4],
        [0.2, 0.5],
        [0.3, 0.6]
    ])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b2'] = np.array([0.1, 0.2])
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))
    
    return y, z1

# 入力値
x = np.array([1., 2.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4.])
# 誤差
loss = functions.mean_squared_error(d, y)
## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[0.1 0.3 0.5]
 [0.2 0.4 0.6]]
shape: (2, 3)

*** 重み2 ***
[[0.1 0.4]
 [0.2 0.5]
 [0.3 0.6]]
shape: (3, 2)

*** バイアス1 ***
[0.1 0.2 0.3]
shape: (3,)

*** バイアス2 ***
[0.1 0.2]
shape: (2,)

##### 順伝播開始 #####
*** 総入力1 ***
[0.6 1.3 2. ]
shape: (3,)

*** 中間層出力1 ***
[0.6 1.3 2. ]
shape: (3,)

*** 総入力2 ***
[1.02 2.29]
shape: (2,)

*** 出力1 ***
[1.02 2.29]
shape: (2,)

出力合計: 3.9

##### 結果表示 #####
*** 中間層出力 ***
[0.6 1.3 2. ]
shape: (3,)

*** 出力 ***
[1.02 2.29]
shape: (2,)

*** 訓練データ ***
[2. 4.]
shape: (2,)

*** 誤差 ***
0.9711249999999999



# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

In [14]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.random.rand(3,5)
    network['W2'] = np.random.rand(5,4)
    network['b1'] = np.random.rand(5)
    network['b2'] = np.random.rand(4)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))
    
    return y, z1

# 入力値
x = np.array([1., 2.,3.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4.,6.,8])
# 誤差
loss = functions.mean_squared_error(d, y)
## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)

##### ネットワークの初期化 #####
*** 重み1 ***
[[0.1570991  0.38604204 0.70482447 0.82452378 0.72999506]
 [0.27937622 0.07771197 0.76182898 0.52391198 0.92258851]
 [0.04695586 0.4396369  0.70629134 0.07384478 0.09398867]]
shape: (3, 5)

*** 重み2 ***
[[0.78263969 0.21610025 0.72185039 0.58912004]
 [0.83540524 0.54218378 0.1675013  0.54877287]
 [0.79013343 0.78425385 0.32143587 0.60942735]
 [0.34963788 0.20047834 0.0233753  0.3004454 ]
 [0.11232293 0.03395003 0.3362552  0.70034865]]
shape: (5, 4)

*** バイアス1 ***
[0.34554179 0.14462518 0.39723573 0.50716923 0.19333855]
shape: (5,)

*** バイアス2 ***
[0.13527115 0.4731895  0.78559489 0.55910559]
shape: (4,)

##### 順伝播開始 #####
*** 総入力1 ***
[1.2022609  2.00500186 4.74459217 2.60105132 3.05047664]
shape: (5,)

*** 中間層出力1 ***
[1.2022609  2.00500186 4.74459217 2.60105132 3.05047664]
shape: (5,)

*** 総入力2 ***
[7.75212275 6.16606077 4.60090889 8.17702756]
shape: (4,)

*** 出力1 ***
[7.75212275 6.16606077 4.60090889 8.17702756]
shape: (4,)

出力合計: 13.603382898137733



# 2値分類（2-3-1ネットワーク）

In [15]:
# 2値分類
# 2-3-1ネットワーク

# ！試してみよう_ノードの構成を 5-10-1 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.array([
        [0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]
    ])
    network['W2'] = np.array([
        [0.2],
        [0.4],
        [0.6]
    ])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b2'] = np.array([0.1])
    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']    

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = functions.sigmoid(u2)
            
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1


# 入力値
x = np.array([1., 2.])
# 目標出力
d = np.array([1])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
*** 総入力1 ***
[0.6 1.3 2. ]
shape: (3,)

*** 中間層出力1 ***
[0.6 1.3 2. ]
shape: (3,)

*** 総入力2 ***
[1.94]
shape: (1,)

*** 出力1 ***
[0.87435214]
shape: (1,)

出力合計: 3.9

##### 結果表示 #####
*** 中間層出力 ***
[0.6 1.3 2. ]
shape: (3,)

*** 出力 ***
[0.87435214]
shape: (1,)

*** 訓練データ ***
[1]
shape: (1,)

*** 誤差 ***
0.13427195993720972



# ！試してみよう_ノードの構成を 5-10-1 に変更してみよう

In [16]:

# ！試してみよう_ノードの構成を 5-10-1 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.random.rand(5,10)
    network['W2'] = np.random.rand(10,1)
    network['b1'] = np.random.rand(10)
    network['b2'] = np.random.rand(1)
    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']    

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = functions.sigmoid(u2)
            
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1


# 入力値
x = np.array([1., 2.,3.,4.,5.])
# 目標出力
d = np.array([1])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
*** 総入力1 ***
[ 8.55195085  3.70871851  7.80889427 12.28327955  9.44869093  9.0242176
 10.28230136  7.217342    7.95524608  7.27691262]
shape: (10,)

*** 中間層出力1 ***
[ 8.55195085  3.70871851  7.80889427 12.28327955  9.44869093  9.0242176
 10.28230136  7.217342    7.95524608  7.27691262]
shape: (10,)

*** 総入力2 ***
[42.34007865]
shape: (1,)

*** 出力1 ***
[1.]
shape: (1,)

出力合計: 83.55755377309933

##### 結果表示 #####
*** 中間層出力 ***
[ 8.55195085  3.70871851  7.80889427 12.28327955  9.44869093  9.0242176
 10.28230136  7.217342    7.95524608  7.27691262]
shape: (10,)

*** 出力 ***
[1.]
shape: (1,)

*** 訓練データ ***
[1]
shape: (1,)

*** 誤差 ***
-9.999999505838704e-08

